theme: jekyll-theme-midnight
title: [Cours ensai informatique 2019-2020]
description: [Ensemble des ressources utilisées et proposées aux élèves dans le cadres des cours d'informatique à l'Ensai par Rémi Pépin]